### PR TITLE
Add test printed circuit board project

### LINKED ISSUE #43: Add test printed circuit board project
Add test Printed Circuit Board (PCB) project. The proposed design was outlined in #42.

Key PCB features (as outlined in #42):
- The PCB will be a breakout board for the [Maxim Integrated MAX6683](https://www.maximintegrated.com/en/products/sensors/MAX6683.html) ([datasheet](https://datasheets.maximintegrated.com/en/ds/MAX6683.pdf)) temperature sensor and system monitor.
- All MAX6683 signals will be brought out to the breakout board's pin headers.
- The signals that are brought out to the breakout board's pin headers will use the same arrangement that is found on the MAX6683.
- Solder jumpers will be used to configure the MAX6683's I2C address (see [Sparkfun's Texas Instruments TMP117 breakout board schematic](https://cdn.sparkfun.com/assets/2/0/f/c/a/SparkFun_TMP117_Qwiic_Schematic_v1.pdf) for reference).
- I2C pull-up resistors will be provided, but the user will be able to cut the normally connected solder jumpers to disable them (see [Sparkfun's Texas Instruments TMP117 breakout board schematic](https://cdn.sparkfun.com/assets/2/0/f/c/a/SparkFun_TMP117_Qwiic_Schematic_v1.pdf) for reference).

This test project will be used to test this repository's Continuous Integration (CI) jobs. The Pull Request (PR) that implements this test project **_should not_** implement fixes for any CI job bugs that are discovered. CI job bugs should be reported in their own issues and fixed by dedicated PRs.

The following CI job features should be verified during development of this feature. CI job failures should be deliberately triggered when possible during development to ensure the CI jobs are working properly.
- (optional) KiCad Library Convention (KLC) compliance violations are detected
    - This is optional because the KLC compliance CI job was copied from https://github.com/apcountryman/prototype-kicad-library-ci where it was already tested. Recommend just using the official part libraries if they support all parts required by the breakout board.
- Electrical Rules Check (ERC) error detection
- Design Rules Check (DRC) error detection
- Schematic PDF generation
- Tradition Bill of Materials (BOM) generation
- Interactive BOM generation
- Production files generation
- PCB renders generation

### PR DESCRIPTION
**Pull request by jaylamb**
_This pull request is currently a work in progress_

## Add test printed circuit board project
A breakout printed circuit board (PCB) containing a Maxim Integrated MAX6683 temperature sensor and system monitor is being added to the repository as a demonstration of the functionality and capability of the repository's continuous integration (CI) pipeline.

Resolves #43.

This pull request:
- [ ] Implements a bug fix
- [ ] Implements an enhancement to an existing feature
- [X] Implements a new feature
- [ ] Performs a refactoring

Please mark the pull request as "Ready for review" and request a review when the pull
request is ready for a review.
If changes are requested, please discuss and/or address the review findings before
requesting a new review.

@apcountryman

### CODE REVIEW

**Comment by jaylamb** [comment]
@apcountryman 

It appears to me that [generate_schematic_pdf](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-schematic-pdf#L71), [generate_traditional_bom](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-traditional-bom#L71), [generate_interactive_bom](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-interactive-bom#L71), [generate_pcb_renders ](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-pcb-renders#L70), and [generate_production_files](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-production-files#L71) all contain an error in the construction of the file string used as the search target.

As a result:
- `generate_schematic_pdf` is searching for `*.pro.sch` files
- `generate_traditional_bom` is searching for `*.pro.sch` files
- `generate_interactive_bom` is searching for `*.pro.kicad_pcb` files
- `generate_production_files` is searching for `*.kicad_pcb.kicad_pcb` files
- `generate_pcb_renders` is searching for `*.pro.kicad_pcb` files

**Comment by apcountryman** [comment]
> @apcountryman
> 
> It appears to me that [generate_schematic_pdf](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-schematic-pdf#L71), [generate_traditional_bom](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-traditional-bom#L71), [generate_interactive_bom](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-interactive-bom#L71), [generate_pcb_renders ](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-pcb-renders#L70), and [generate_production_files](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-production-files#L71) all contain an error in the construction of the file string used as the search target.
> 
> As a result:
> 
> * `generate_schematic_pdf` is searching for `*.pro.sch` files
> * `generate_traditional_bom` is searching for `*.pro.sch` files
> * `generate_interactive_bom` is searching for `*.pro.kicad_pcb` files
> * `generate_production_files` is searching for `*.kicad_pcb.kicad_pcb` files
> * `generate_pcb_renders` is searching for `*.pro.kicad_pcb` files

Yup. Also looks like the PCB renders generation script isn't identifying projects correctly (searches for `.kicad_pcb` instead of `.pro` files). For whatever reason I thought `basename` removed suffixes automatically but it doesn't. Since we know what the suffix is in each case, we can alter the existing `basename` calls to remove the suffix. I'll get these fixed shortly.

**Comment by apcountryman** [comment]
> > @apcountryman
> > It appears to me that [generate_schematic_pdf](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-schematic-pdf#L71), [generate_traditional_bom](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-traditional-bom#L71), [generate_interactive_bom](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-interactive-bom#L71), [generate_pcb_renders ](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-pcb-renders#L70), and [generate_production_files](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-production-files#L71) all contain an error in the construction of the file string used as the search target.
> > As a result:
> > 
> > * `generate_schematic_pdf` is searching for `*.pro.sch` files
> > * `generate_traditional_bom` is searching for `*.pro.sch` files
> > * `generate_interactive_bom` is searching for `*.pro.kicad_pcb` files
> > * `generate_production_files` is searching for `*.kicad_pcb.kicad_pcb` files
> > * `generate_pcb_renders` is searching for `*.pro.kicad_pcb` files
> 
> Yup. Also looks like the PCB renders generation script isn't identifying projects correctly (searches for `.kicad_pcb` instead of `.pro` files). For whatever reason I thought `basename` removed suffixes automatically but it doesn't. Since we know what the suffix is in each case, we can alter the existing `basename` calls to remove the suffix. I'll get these fixed shortly.

@jaylamb the fix has been merged into `main`. Please let me know whether it worked.

**Comment by jaylamb** [comment]
> > > @apcountryman
> > > It appears to me that [generate_schematic_pdf](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-schematic-pdf#L71), [generate_traditional_bom](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-traditional-bom#L71), [generate_interactive_bom](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-interactive-bom#L71), [generate_pcb_renders ](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-pcb-renders#L70), and [generate_production_files](https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/fb3a4e0464be93d8ed5ed92cb32a5f847391f712/ci/generate-production-files#L71) all contain an error in the construction of the file string used as the search target.
> > > As a result:
> > > 
> > > * `generate_schematic_pdf` is searching for `*.pro.sch` files
> > > * `generate_traditional_bom` is searching for `*.pro.sch` files
> > > * `generate_interactive_bom` is searching for `*.pro.kicad_pcb` files
> > > * `generate_production_files` is searching for `*.kicad_pcb.kicad_pcb` files
> > > * `generate_pcb_renders` is searching for `*.pro.kicad_pcb` files
> > 
> > 
> > Yup. Also looks like the PCB renders generation script isn't identifying projects correctly (searches for `.kicad_pcb` instead of `.pro` files). For whatever reason I thought `basename` removed suffixes automatically but it doesn't. Since we know what the suffix is in each case, we can alter the existing `basename` calls to remove the suffix. I'll get these fixed shortly.
> 
> @jaylamb the fix has been merged into `main`. Please let me know whether it worked.

`generate_interactive_bom` and `generate_production_files` are still looking in the wrong place:

```error: pathspec '/home/runner/work/prototype-kicad-project-ci-cd/prototype-kicad-project-ci-cd/max6683-breakout.kicad_pcb' did not match any file(s) known to git```

In both cases, I think replacing `local -r layout=$repository/$project_name.kicad_pcb` with `local -r layout=$repository/$project_name/$project_name.kicad_pcb` will do the trick.

**Comment by jaylamb** [comment]
I'm getting some other failures on CI jobs that seem to be based around `pcbnew`. At the moment I'm unsure why, but I'm wondering if it's related to the recent KiCad major version update.

For example, I see three instances of:
`AttributeError: module 'pcbnew' has no attribute 'GetBuildVersion'`

**Comment by apcountryman** [comment]
> I'm getting some other failures on CI jobs that seem to be based around `pcbnew`. At the moment I'm unsure why, but I'm wondering if it's related to the recent KiCad major version update.
> 
> For example, I see three instances of: `AttributeError: module 'pcbnew' has no attribute 'GetBuildVersion'`

All the tools we are relying on support KiCad 5, but it looks like we need to both update the version of the tools we are using and install a newer version of KiCad 5 (see https://github.com/INTI-CMNB/KiBot/commit/409df8cca0bcfc6950d98935140602267ca6264c, https://github.com/INTI-CMNB/KiBot/issues/45, and https://github.com/INTI-CMNB/KiBot/issues/36).

I'll update my tool forks in a bit so that the submodules can be updated. Instructions for installing a newer version of KiCad 5 can be found in the "5.1.12 previous stable release" section of https://www.kicad.org/download/ubuntu/.

**Comment by jaylamb** [comment]
> > I'm getting some other failures on CI jobs that seem to be based around `pcbnew`. At the moment I'm unsure why, but I'm wondering if it's related to the recent KiCad major version update.
> > For example, I see three instances of: `AttributeError: module 'pcbnew' has no attribute 'GetBuildVersion'`
> 
> All the tools we are relying on support KiCad 5, but it looks like we need to both update the version of the tools we are using and install a newer version of KiCad 5 (see [INTI-CMNB/KiBot@409df8c](https://github.com/INTI-CMNB/KiBot/commit/409df8cca0bcfc6950d98935140602267ca6264c), [INTI-CMNB/KiBot#45](https://github.com/INTI-CMNB/KiBot/issues/45), and [INTI-CMNB/KiBot#36](https://github.com/INTI-CMNB/KiBot/issues/36)).
> 
> I'll update my tool forks in a bit so that the submodules can be updated. Instructions for installing a newer version of KiCad 5 can be found in the "5.1.12 previous stable release" section of https://www.kicad.org/download/ubuntu/.

Not sure if that page caught an update in the last few days, but I didn't see a `5.1.12 previous stable release` section. [Is adding this to the CI jobs the idea](https://launchpad.net/~kicad/+archive/ubuntu/kicad-5.1-releases)?

**Comment by apcountryman** [comment]
> > > I'm getting some other failures on CI jobs that seem to be based around `pcbnew`. At the moment I'm unsure why, but I'm wondering if it's related to the recent KiCad major version update.
> > > For example, I see three instances of: `AttributeError: module 'pcbnew' has no attribute 'GetBuildVersion'`
> > 
> > 
> > All the tools we are relying on support KiCad 5, but it looks like we need to both update the version of the tools we are using and install a newer version of KiCad 5 (see [INTI-CMNB/KiBot@409df8c](https://github.com/INTI-CMNB/KiBot/commit/409df8cca0bcfc6950d98935140602267ca6264c), [INTI-CMNB/KiBot#45](https://github.com/INTI-CMNB/KiBot/issues/45), and [INTI-CMNB/KiBot#36](https://github.com/INTI-CMNB/KiBot/issues/36)).
> > I'll update my tool forks in a bit so that the submodules can be updated. Instructions for installing a newer version of KiCad 5 can be found in the "5.1.12 previous stable release" section of https://www.kicad.org/download/ubuntu/.
> 
> Not sure if that page caught an update in the last few days, but I didn't see a `5.1.12 previous stable release` section. [Is adding this to the CI jobs the idea](https://launchpad.net/~kicad/+archive/ubuntu/kicad-5.1-releases)?

Looks like it's been updated. What you linked to looks familiar, but I vaguely remember instructions for installing KiCad from a specific package source.

It might be best to just switch to KiCad 6 at this point if the CI/CD tools support it...

**Comment by apcountryman** [comment]
@jaylamb the initial KiCad 6 transition work has been completed (on `main`).

**Review by apcountryman — COMMENTED** [review]
The schematic looks good enough for this prototype, but I do have some notes for your consideration:
- Sparkfun's Texas Instruments TMP117 breakout connects its SCL and SDA pull-up resistors to 3.3V via a solder jumper by default. Consider doing the same for this board
- Sparkfun's Texas Instruments TMP117 breakout uses 2.2k pull-ups for SCL and SDA. Consider doing the same here to better support higher SCL speeds.
- Solder jumpers and power flags should be excluded from the bill of materials.
- Consider connecting the ADD pin to GND via a solder jumper by default instead of SDA.
- Consider adding a default connect solder jumper between the !ALERT pin's pull-up resistor and 3.3V (Sparkfun's Texas Instruments TMP117 breakout does this for the TMP117's !INT pin).

Some notes for things other than the schematic:
- I believe the `max6683-breakout/max6683-breakout.pro` and `max6683-breakout/max6683-breakout.sch` files are KiCad 5 files and thus should be removed.
- The CI scripts assume that KiCad project/schematic/layout files are located at the root of the repository. Placing the MAX6683 breakout's KiCad files in a sub directory is causing some of the current CI job failures.

**Comment by apcountryman** [comment]
Looks like the failing CI jobs are installing KiCad 5 from the Ubuntu package repositories instead of KiCad 6 from the KiCad PPA.

**Review by apcountryman — COMMENTED** [review]
We should discuss what the end goal of this prototype is before review findings are addressed and/or a more thorough review is conducted (this review was focused on the CI jobs).

Review notes:
- KLC compliance CI jobs were successfully tested by the `prototype-kicad-library-ci` project.
- Not sure if the ERC CI job successfully detected and reported ERC errors. If it did, it may have done so before the transition to KiCad 6.
- The DRC CI job successfully detected and reported DRC errors.
- Interactive BOM looks good. Output file name should be changed to reflect the project name instead of just being `ibom.html`.
- The SVG PCB renders look good but it looks like the JPG and PNG renders weren't generated correctly (JPG is all black, PNG is all transparent).
- Production files are being generated and the file content looks reasonable. Didn't bother opening them in a viewer.
- Schematic PDF looks good.
- Traditional BOMs look good. File names are a bit off (probably due to not having a KiBoM configuration file). Headers are missing manufacturer and part number info.

Things that may need to be considered depending on the end goal of the prototype:
- Electrical and design rule violations severity may need to be adjusted.
- Adding copyright and license info the schematic, layout, and certain generated files.
- Adding project info to the schematic, layout, and certain generated files.
- Adding version control information to the schematic, layout, and certain generated files.
- Changing CI job artifact naming to include the project name and version control information.

**Review by apcountryman — APPROVED** [review]
LGTM

**Pull request merged**
